name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
        rm -rf PYRO-RENAME-BOT
        git config --global user.email yashoswal18@gmail.com
        git config --global user.name mergebot
        git clone --branch main https://github.com/Itzmepapa123/PYRO-RENAME-BOT.git
        cd PYRO-RENAME-BOT
        git fetch origin
        git checkout main
        git pull origin main
        docker build -t main:latest .
        docker stop name || true
        docker rm name || true
        docker run -d --name name -p 9223:9223 main:latest
        EOF
